name: API Tests with Pytest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 步骤1: 检出代码
      - uses: actions/checkout@v4

      # 步骤2: 设置Python环境
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      # 步骤3: 安装依赖（包含Allure命令行工具）
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest allure-pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # 安装Allure命令行工具
          sudo apt-get update
          sudo apt-get install -y allure
          # 验证安装
          allure --version

      # 步骤4: 创建报告目录
      - name: Create reports directory
        run: mkdir -p reports/allure-results

      # 步骤5: 运行测试并生成报告
      - name: Run tests and generate reports
        run: |
          pytest Tests/ \
            --junitxml=reports/junit.xml \
            --alluredir=reports/allure-results

      # 步骤6: 生成Allure HTML报告
      - name: Generate Allure report
        run: |
          allure generate reports/allure-results -o reports/allure-report --clean
          # 添加环境信息
          echo "python_version=3.8" >> reports/allure-results/environment.properties
          echo "os=ubuntu-latest" >> reports/allure-results/environment.properties

      # 步骤7: 上传测试结果
      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports-${{ github.run_id }}
          path: |
            reports/junit.xml
            reports/allure-report/
          retention-days: 7